const mongoose = require("mongoose");

const FineDetailsSchema=new mongoose.Schema(
    {
        fineID:{
            type:String,
            required:true
        },
        fineDateTime:{
            type:String,
            required:true
        }, 
        natureOfOffence:{
            type:String,
            required:true
        },
        fineAmount:{
            type:String,
            required:true
        },
        vehicleNumber:{
            type:String,
            required:true
        },
        PayStatus:{
            type:Boolean,
            required:true
        },
        LIN:{
            type:String,
            required:true
        },
        place:{
            type:String,
            required:true
        },
        fineList:{
            type:[],
            required:true
        },
        DriverFirstName:{
            type:String,
            required:true
        },
        DriverLastName:{
            type:String,
            required:true
        },
        DriverEmail:{
            type:String,
            required:true
        },
        DriverContact:{
            type:String,
            required:true
        },
        DriverAddress:{
            type:String,
            required:true
        },
        PoliceOfficerName:{
            type:String,
            required:true
        },
        PoliceOfficerRank:{
            type:String,
            required:true
        },
        PoliceStation:{
            type:String,
            required:true
        }
    }
)
const FineDetails=mongoose.model("FineDetails",FineDetailsSchema);
module.exports=FineDetails;